# Generated by Django 2.1.1 on 2018-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=50)),
                ('refresh_token', models.CharField(blank=True, max_length=50)),
                ('expire_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
